version: "3.2"
services:
  nodejs:
    build: .
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mba-mysql-order
      - MYSQL_USER=admin
      - MYSQL_PASS=admin123
      - MYSQL_DB=mba_microservices_order
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "4008:4008"
    container_name: mba-nodejs-app
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=mba_microservices_order
    volumes:
      - mysql_order:/var/lib/mysql
    container_name: mba-mysql-order
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mba-mysql-order
      - PMA_PORT= 3308
    volumes:
      - /sessions
    container_name: mba-phpmyadmin-order
networks:
  frontend:
  backend:
  sb:
    driver: bridge
volumes:
  mysql_order:
